# Site
title: Dalstroem
description: Programmer, Nerd, Gamer and Beardman.

author:
  name: Dennis Dalstrøm

baseurl: '/'
permalink: pretty
timezone: Europe/Copenhagen

google_analytics: UA-67502425-2

# Build
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

environment: production

# Others
exclude: [CNAME, Gemfile, jekyll-serve, LICENSE, README.md]
