# Site
name: Dalstroem
description: Programmer, Nerd, Gamer and Beardman.

author:
  name: Dennis Dalstrøm

url: http://dalstroem.com
baseurl: '/'
permalink: pretty
timezone: Europe/Copenhagen

google_analytics: UA-67502425-2

disqus:
  shortname: dalstroem

# Build
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

environment: production

# Others
gems: [jekyll-feed]

exclude: [CNAME, Gemfile, jekyll-serve, LICENSE, README.md]
